spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?useSSL=false&serverTimezone=UTC
    username: root
    password: 3312
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: ariel
      password: 1234x
